var read=require('readline-sync');
var d=read.questionInt("Enter Day ");
var m=read.questionInt("Enter Month ");
var y=read.questionInt("Enter year ");
y0 = y-parseInt((14-m)/ 12);
console.log(y0);
x = y0 + parseInt(y0/4)-parseInt(y0/100) + parseInt(y0/400);
console.log(x);
m0 =m +12*parseInt( (14- m) / 12)-2;
d0 = (d + x + parseInt(31*(m0 / 12)))% 7;
console.log(parseInt(d0));